#spring.application.name=userauth-services
#spring.datasource.driver-class=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/caaar
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#server.port=0
#eureka.client.serviceurl.defaultZone=http://localhost:9014/eureka


#-------------------
spring.application.name=userauth-services
server.port=0
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# MODIFIED: Database Configuration
spring.datasource.driver-class=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/caaar}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

# MODIFIED: Eureka Configuration
eureka.client.serviceurl.defaultZone=${EUREKA_URI:http://localhost:9014/eureka}